package cliente.sop_corba;


/**
* cliente/sop_corba/Paciente.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesPacientes.idl
* sábado 20 de junio de 2020 03:34:21 PM COT
*/

public interface Paciente extends PacienteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Paciente
