package servidorAlertas.dto;


/**
* servidorAlertas/dto/HistorialAlertasDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesPacientes.idl
* sábado 20 de junio de 2020 05:13:41 PM COT
*/

public final class HistorialAlertasDTO implements org.omg.CORBA.portable.IDLEntity
{
  public servidorAlertas.dto.AlertaDTO alertas[] = null;
  public servidorAlertas.dto.PacienteDTO objPaciente = null;

  public HistorialAlertasDTO ()
  {
  } // ctor

  public HistorialAlertasDTO (servidorAlertas.dto.AlertaDTO[] _alertas, servidorAlertas.dto.PacienteDTO _objPaciente)
  {
    alertas = _alertas;
    objPaciente = _objPaciente;
  } // ctor

} // class HistorialAlertasDTO
