package servidorAlertas.dto;


/**
* servidorAlertas/dto/IndicadoresDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesPacientes.idl
* sábado 20 de junio de 2020 05:46:11 PM COT
*/

public final class IndicadoresDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int frecuenciaCardiaca = (int)0;
  public int frecuenciaRespiratoria = (int)0;
  public float temperatura = (float)0;

  public IndicadoresDTO ()
  {
  } // ctor

  public IndicadoresDTO (int _frecuenciaCardiaca, int _frecuenciaRespiratoria, float _temperatura)
  {
    frecuenciaCardiaca = _frecuenciaCardiaca;
    frecuenciaRespiratoria = _frecuenciaRespiratoria;
    temperatura = _temperatura;
  } // ctor

} // class IndicadoresDTO
