package servidorAlertas.dto;


/**
* servidorAlertas/dto/PacienteDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesPacientes.idl
* sábado 20 de junio de 2020 05:46:11 PM COT
*/

public final class PacienteDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String nombres = null;
  public String apellidos = null;
  public String tipo_id = null;
  public int id = (int)0;
  public String direccion = null;

  public PacienteDTO ()
  {
  } // ctor

  public PacienteDTO (String _nombres, String _apellidos, String _tipo_id, int _id, String _direccion)
  {
    nombres = _nombres;
    apellidos = _apellidos;
    tipo_id = _tipo_id;
    id = _id;
    direccion = _direccion;
  } // ctor

} // class PacienteDTO
