package servidorNotificaciones.sop_corba;


/**
* servidorNotificaciones/sop_corba/Notificaciones.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesPacientes.idl
* sábado 20 de junio de 2020 03:34:21 PM COT
*/

public interface Notificaciones extends NotificacionesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Notificaciones
