package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/GestionPacientes.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesPacientes.idl
* sábado 20 de junio de 2020 03:34:21 PM COT
*/

public interface GestionPacientes extends GestionPacientesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionPacientes
