module servidorAlertas{
    module sop_corba{
        interface Paciente;
        interface GestionPacientes{
            struct PacienteDTO{
                string nombres;
                string apellidos;
                string tipo_id;
                long id;
                string direccion;
            };

            struct IndicadoresDTO{
                int frecuenciaCardiaca;
                int frecuenciaRespiratoria;
                float temperatura;
            }

            struct AlertaDTO{
                IndicadoresDTO indicadores;
                Date fechaHora;
                int puntuacion;
            }

            struct historialAlertasDTO{
                AlertaDTO alertas[6];
                PacienteDTO objPaciente;
            }

            boolean registrarPaciente(in PacienteDTO objPaciente, in IPaciente refCliente, out string resultado);
            boolean enviarIndicadores(in long idPaciente,in IndicadoresDTO objIndicadores);
            boolean establecerMaxPacientes(int num);
            int getMaxPacientes();
            int getNumRegistros();
        };
    };
};